name: Build with Gradle

on:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/build.yml
      - src/**
  pull_request:
    paths:
      - .github/workflows/build.yml
      - src/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Support for ipv6
      - name: Set up WARP
        uses: fscarmen/warp-on-actions@v1.1
        if: contains(github.ref_name, 'main')
        with:
          stack: dual
      - uses: actions/checkout@v4
      - run: chmod +x gradlew
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper
          cache-overwrite-existing: true
          cache-read-only: false
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"
      - name: Build
        run: ./gradlew build
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        if: success() && contains(github.ref_name, 'main')
        with:
          path: build/libs/*.jar